# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: trusty
language: r
sudo: false

r_github_packages: 
  - USCBiostats/amcmc
  - USCBiostats/polygons

r:
  - release
  - oldrel

os:
  - linux
  - osx
  
osx_image: xcode7.3

env:
 global:
   - CRAN: http://cran.rstudio.com

after_success:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then Rscript -e 'covr::codecov()'; fi
